// diffusion-sampler concept page -- what happens at INFERENCE time.
//
// Sampling from a diffusion / flow-matching model is NUMERICAL INTEGRATION of a
// learned field. Nothing here is generated by a neural net: the toy data
// distribution is a two-moons mixture of narrow Gaussians, for which the exact
// probability-flow velocity is closed form -- so every arrow and every particle
// step on screen is real arithmetic you can hover and read.
//
//   interpolant   x_t = a(t)*x_data + s(t)*x_noise,   t: 0 (noise) -> 1 (data)
//     diffusion path   a = sin(pi t/2),  s = cos(pi t/2)     (curved, schedule-shaped)
//     rectified flow   a = t,            s = 1 - t           (straight conditional path)
//   posterior mean   E[x_data | x_t = x] = (1 - c*a)*M(x) + c*x,  c = a*var/tau^2
//   velocity         u(x,t) = a'*E1 + (s'/s)*(x - a*E1)
//   score            grad log p_t(x) = -(x - a*E1)/s^2
//   ODE step         x <- x + u*h                                  (deterministic)
//   SDE step         x <- x + (u + (g^2/2)*score)*h + g*sqrt(h)*z   (stochastic, g = churn*s)
//
// The SDE keeps the same marginals as the ODE -- it is the same field, re-noised
// each step -- so the toggle isolates exactly one thing: whether noise is
// re-injected along the way.
//
// Interactions: transport steps the integration (autoplay + loop); DRAG a
// particle's hollow start marker to re-integrate its whole trajectory under
// your hand; HOVER a field arrow or a particle for the field value and the
// update arithmetic; step-count / interpolant / ODE-vs-SDE / churn controls;
// URL hooks (?step, ?steps, ?path, ?sde, ?churn, ?seed, ?drag, ?hover) so one
// URL replays one exact run.
//
// Scope note: this page is the SAMPLER. The training objective and the noising
// schedule are the diffusion-noise page; conditioning and guidance scale are
// the guidance page.
//
// On straightness, measured rather than asserted: the linear interpolant makes
// the CONDITIONAL path (noise sample -> datum) exactly a straight segment, which
// is what the dashed ghost draws. The MARGINAL trajectory the sampler integrates
// is a different object, and on this toy the linear interpolant does not
// straighten it -- the page prints both so the reader can check. Genuine
// straightening needs reflow, and whether straightness is what buys the low step
// count is disputed (see the third link below).
//
// Sources: Karras et al., "Elucidating the Design Space of Diffusion-Based
// Generative Models", https://arxiv.org/abs/2206.00364 (schedule / scaling /
// sampler as orthogonal knobs); Liu et al., "Flow Straight and Fast",
// https://arxiv.org/abs/2209.03003 (rectified flow); and the dissent on
// straightness, https://arxiv.org/abs/2410.07303.
import { mount } from '../framework/layout.js';
import { T, alphaOf } from '../framework/theme.js';
import { seededRandn } from '../framework/tensor.js';

// ---------------------------------------------------------------- toy data --
// Two moons, as a mixture of K isotropic Gaussians of width MODE_SD. Equal
// weights, so the mixture responsibilities below reduce to a softmax over
// squared distances.
const MODE_SD = 0.06, MODE_VAR = MODE_SD * MODE_SD;
const MOONS = (() => {
  const pts = [], K = 48;
  for (let i = 0; i < K; i++) { const th = Math.PI * i / (K - 1); pts.push([Math.cos(th), Math.sin(th)]); }
  for (let i = 0; i < K; i++) { const th = Math.PI * i / (K - 1); pts.push([1 - Math.cos(th), 0.5 - Math.sin(th)]); }
  return pts.map(([x, y]) => [(x - 0.5) * 1.25, (y - 0.25) * 1.25]);
})();
const HALF = 2.6;                       // math-space half-extent drawn
const REF_STEPS = 200;                  // deterministic reference integration
const LADDER = [4, 10, 50];             // the side-by-side step counts

// Interpolant coefficients a(t), s(t) and their derivatives.
function coefs(t, path) {
  if (path === 'linear') return { a: t, s: 1 - t, ad: 1, sd: -1 };
  const h = Math.PI / 2;
  return { a: Math.sin(h * t), s: Math.cos(h * t), ad: h * Math.cos(h * t), sd: -h * Math.sin(h * t) };
}

// The exact probability-flow velocity + score of the toy mixture at (x, y, t).
function field(x, y, t, path) {
  const { a, s, ad, sd } = coefs(t, path);
  const sig = Math.max(s, 1e-3);
  const tau2 = a * a * MODE_VAR + sig * sig;
  let best = Infinity;
  const d = new Float64Array(MOONS.length);
  for (let k = 0; k < MOONS.length; k++) {
    const dx = x - a * MOONS[k][0], dy = y - a * MOONS[k][1];
    d[k] = dx * dx + dy * dy; if (d[k] < best) best = d[k];
  }
  let wsum = 0, mx = 0, my = 0;
  for (let k = 0; k < MOONS.length; k++) {
    const w = Math.exp(-(d[k] - best) / (2 * tau2));
    wsum += w; mx += w * MOONS[k][0]; my += w * MOONS[k][1];
  }
  mx /= wsum; my /= wsum;                                   // M(x) = posterior-mean mode
  const c = a * MODE_VAR / tau2;
  const e1x = (1 - c * a) * mx + c * x, e1y = (1 - c * a) * my + c * y;   // E[x_data | x_t]
  const rx = x - a * e1x, ry = y - a * e1y;                 // = s * E[noise | x_t]
  return {
    a, s: sig, ad, sd, e1x, e1y,
    ux: ad * e1x + (sd / sig) * rx, uy: ad * e1y + (sd / sig) * ry,
    sx: -rx / (sig * sig), sy: -ry / (sig * sig),
  };
}

// ------------------------------------------------------------- integration --
// Deterministic per-(seed, particle, step) noise: the same URL replays the same
// run, and a step-count change re-uses the same draws in the same order.
function gauss2(seed, pi, i) {
  const mix = (a, b, c) => { let h = (Math.imul(a, 374761393) + Math.imul(b, 668265263) + Math.imul(c, 2246822519)) >>> 0; h = Math.imul(h ^ (h >>> 13), 1274126177) >>> 0; return ((h ^ (h >>> 16)) >>> 8) / 16777216; };
  const u = Math.max(1e-7, mix(seed + 1, pi + 17, i + 3)), v = mix(seed + 101, pi + 5, i + 61);
  const r = Math.sqrt(-2 * Math.log(u));
  return [r * Math.cos(2 * Math.PI * v), r * Math.sin(2 * Math.PI * v)];
}
const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);

// One trajectory: N Euler (ODE) or Euler-Maruyama (SDE) steps from t=0 to t=1.
// Returns the full polyline [x0,y0, x1,y1, ...] of length 2*(N+1).
function integrate(x0, y0, N, cfg, pi) {
  const out = new Float64Array(2 * (N + 1));
  let x = x0, y = y0; out[0] = x; out[1] = y;
  const h = 1 / N;
  for (let i = 0; i < N; i++) {
    const f = field(x, y, i * h, cfg.path);
    let dx = f.ux * h, dy = f.uy * h;
    if (cfg.sde && cfg.churn > 0) {
      const g = cfg.churn * f.s;
      dx += 0.5 * g * g * f.sx * h; dy += 0.5 * g * g * f.sy * h;
      const z = gauss2(cfg.seed, pi, i), rt = g * Math.sqrt(h);
      dx += rt * z[0]; dy += rt * z[1];
    }
    x = clamp(x + dx, -6, 6); y = clamp(y + dy, -6, 6);
    out[2 * i + 2] = x; out[2 * i + 3] = y;
  }
  return out;
}

// Distance from a point to the nearest data mode -- the "is it on the manifold"
// proxy. Integration error shows up here first, as smeared fine structure.
function offManifold(x, y) {
  let best = Infinity;
  for (let k = 0; k < MOONS.length; k++) { const dx = x - MOONS[k][0], dy = y - MOONS[k][1]; const d = dx * dx + dy * dy; if (d < best) best = d; }
  return Math.sqrt(best);
}

// Summary metrics for a set of trajectories against a deterministic reference.
function metrics(trajs, refs) {
  let dref = 0, off = 0, straight = 0, n = trajs.length;
  for (let p = 0; p < n; p++) {
    const tr = trajs[p], L = tr.length / 2 - 1;
    const ex = tr[2 * L], ey = tr[2 * L + 1];
    dref += Math.hypot(ex - refs[p][0], ey - refs[p][1]);
    off += offManifold(ex, ey);
    let len = 0;
    for (let i = 0; i < L; i++) len += Math.hypot(tr[2 * i + 2] - tr[2 * i], tr[2 * i + 3] - tr[2 * i + 1]);
    const chord = Math.hypot(ex - tr[0], ey - tr[1]);
    straight += chord > 1e-6 ? len / chord : 1;
  }
  return { dref: dref / n, off: off / n, straight: straight / n };
}

// ------------------------------------------------------------------ state ---
let cur = null;        // { startSig, starts, refSig, refs, trajs, N }
let lad = null;        // { sig, panels: [{N, trajs, m}] }
let plot = null;       // main plot rect + math->px mapping (captured in draw)
let ladRects = [];     // mini-panel rects
let grab = null;       // particle index whose start marker is being dragged
let arrowCells = [];   // hover targets for the field arrows

const cfgOf = (st) => ({ path: st.path, sde: !!st.sde, churn: st.churn, seed: st.seed | 0 });
const cfgSig = (st) => `${st.path}|${st.sde ? 1 : 0}|${st.churn}|${st.seed}|${st.P}`;

function makeStarts(st) {
  const P = st.P | 0, z = seededRandn((st.seed | 0) * 7 + 1, 2 * P, { std: 1 });
  const s = new Float64Array(2 * P);
  for (let i = 0; i < 2 * P; i++) s[i] = z[i];
  return s;
}

// Rebuild every trajectory (and the deterministic reference endpoints) for the
// current controls. Called by the transport, so it re-runs on any rebuild key.
function buildData(st) {
  const P = st.P | 0, N = Math.max(1, st.steps | 0), cfg = cfgOf(st);
  const startSig = `${st.seed}|${P}`;
  if (!cur || cur.startSig !== startSig) cur = { startSig, starts: makeStarts(st) };
  const refSig = `${startSig}|${st.path}`;
  if (cur.refSig !== refSig) {
    cur.refSig = refSig;
    cur.refs = [];
    for (let p = 0; p < P; p++) {
      const r = integrate(cur.starts[2 * p], cur.starts[2 * p + 1], REF_STEPS, { ...cfg, sde: false }, p);
      cur.refs.push([r[2 * REF_STEPS], r[2 * REF_STEPS + 1]]);
    }
  }
  reintegrate(st);
  return Array.from({ length: N + 1 }, (_, i) => ({
    i, t: i / N,
    label: i === 0 ? `t=0 — ${P} noise samples, straight off N(0, I)` : `step ${i}/${N}: t=${(i / N).toFixed(3)}, x ← x + ${st.sde ? '(u + ½g²·score)·h + g√h·z' : 'u·h'}`,
  }));
}

function reintegrate(st, only) {
  const P = st.P | 0, N = Math.max(1, st.steps | 0), cfg = cfgOf(st);
  if (!cur.trajs || cur.trajs.length !== P || cur.N !== N) { cur.trajs = new Array(P); cur.N = N; only = undefined; }
  for (let p = 0; p < P; p++) {
    if (only !== undefined && p !== only) continue;
    cur.trajs[p] = integrate(cur.starts[2 * p], cur.starts[2 * p + 1], N, cfg, p);
  }
  cur.m = metrics(cur.trajs, cur.refs);
}

// The 4 / 10 / 50 ladder: the SAME seed and the SAME field at three step
// counts. Cached, because it is independent of the transport position.
function buildLadder(st) {
  const sig = cfgSig(st);
  if (lad && lad.sig === sig) return lad;
  const P = st.P | 0, cfg = cfgOf(st);
  const run = (N, c) => { const trajs = []; for (let p = 0; p < P; p++) trajs.push(integrate(cur.starts[2 * p], cur.starts[2 * p + 1], N, c, p)); return { N, trajs, m: metrics(trajs, cur.refs) }; };
  lad = { sig, panels: LADDER.map((N) => run(N, cfg)) };
  // The deterministic 4-step run is kept alongside as the control the stochastic
  // one is compared against (same seed, same field, same step count).
  lad.odeOff4 = cfg.sde ? run(LADDER[0], { ...cfg, sde: false }).m.off : lad.panels[0].m.off;
  return lad;
}

// ------------------------------------------------------------------ draw ----
function drawManifold(ctx, map, r, alpha) {
  ctx.save(); ctx.fillStyle = alphaOf(T.ok, alpha);
  for (let k = 0; k < MOONS.length; k++) { const p = map(MOONS[k][0], MOONS[k][1]); ctx.beginPath(); ctx.arc(p.x, p.y, r, 0, 6.2832); ctx.fill(); }
  ctx.restore();
}

function panelFrame(ctx, R, title, colour) {
  ctx.save();
  ctx.fillStyle = alphaOf('n14', 0.03); ctx.fillRect(R.x, R.y, R.w, R.h);
  ctx.strokeStyle = T.n5; ctx.lineWidth = 1; ctx.strokeRect(R.x + 0.5, R.y + 0.5, R.w - 1, R.h - 1);
  if (title) { ctx.fillStyle = colour || T.n11; ctx.font = '10px ui-monospace, monospace'; ctx.textBaseline = 'top'; ctx.fillText(title, R.x + 5, R.y + 4); }
  ctx.restore();
}

mount({
  mount: 'body',
  title: 'diffusion-sampler — integrating a learned field',
  blurb: 'Sampling is not "denoising N times until it looks good" — it is numerical integration of a velocity field, from a noise sample at t=0 to a data sample at t=1. The field here is exact (a two-moons mixture, closed form), so the arrows and every particle update are real arithmetic. Step count is the DISCRETISATION dial: fewer steps means larger integration error, which shows up first as points drifting off the manifold — lost fine texture, not obvious breakage. The interpolant toggle changes only the PATH — diffusion (schedule-shaped, curved) vs rectified flow (the conditional path from a noise sample to a datum is a straight line) — with the same field formula, the same integrator and the same particles. The dashed ghost is that conditional path, and it is the thing the toggle straightens; the page also MEASURES the marginal trajectory the sampler actually walks, which the linear interpolant does not straighten for free. The sampler toggle changes only whether noise is re-injected each step: the ODE is reproducible and invertible; the SDE self-corrects accumulated error but lands somewhere else. Drag a hollow start marker to re-integrate that trajectory under your hand; hover an arrow or a particle for its field value and update arithmetic. The 4 / 10 / 50 panels on the right are the same seed and the same field at three step counts.',
  prefer: 'canvas2d',
  aspect: '16 / 9',
  autoplay: true,
  challenges: [
    { goal: 'Land the run on the data manifold: mean off-manifold distance below 0.05.', hint: 'raise the step count — the field is fine, the integration is what is coarse.', check: (api) => ({ solved: (api.probe.off ?? 9) < 0.05, detail: `off-manifold = ${(api.probe.off ?? 0).toFixed(3)} (need < 0.05)` }) },
    { goal: 'Show that step count is a discretisation dial: bring Δ vs the 200-step reference below 0.01 without touching the field.', hint: 'the only knob that changes the integration error is the step count (and the ODE, which has a reference to converge to).', check: (api) => ({ solved: !api.probe.sde && (api.probe.dref ?? 9) < 0.01, detail: api.probe.sde ? 'the SDE has no fixed endpoint to converge to — try the ODE' : `Δref = ${(api.probe.dref ?? 0).toFixed(4)} (need < 0.01)` }) },
    { goal: 'Find a setting where 4 steps lands CLOSER to the manifold than the deterministic 4-step run.', hint: 'stochastic sampling re-injects noise and the score term pulls each step back onto the data — compare the 4-step panel with the SDE on and off.', check: (api) => ({ solved: !!api.probe.sde && (api.probe.lad4 ?? 9) < (api.probe.odeLad4 ?? 0), detail: api.probe.sde ? `SDE 4-step off ${(api.probe.lad4 ?? 0).toFixed(3)} vs ODE 4-step off ${(api.probe.odeLad4 ?? 0).toFixed(3)}` : 'turn the stochastic sampler on' }) },
  ],
  controls: (c, page) => {
    c.select('path', { label: 'interpolant (the path)', options: [{ value: 'diffusion', label: 'diffusion (curved)' }, { value: 'linear', label: 'rectified flow (straight)' }], value: 'diffusion', rebuild: true });
    c.toggle('sde', { label: 'stochastic sampler (SDE)', value: false, rebuild: true });
    c.slider('churn', { label: 'noise re-injection (g = churn·σ)', min: 0, max: 1.6, step: 0.05, value: 0.8, rebuild: true });
    c.slider('steps', { label: 'integration steps', min: 2, max: 80, step: 1, value: 10, rebuild: true });
    c.stepper('P', { label: 'particles', min: 4, max: 24, value: 10 });
    c.toggle('guide', { label: 'show conditional paths', value: true });
    c.slider('seed', { label: 'seed', min: 0, max: 99, step: 1, value: 3, rebuild: true });
    c.transport({ compute: () => buildData(page.state), speed: 9, loop: true });
  },
  onPointer: (page, ev) => {
    if (!cur || !plot) return;
    const st = page.state, P = st.P | 0;
    if (ev.type === 'down') {
      grab = null;
      for (let p = 0; p < P; p++) {
        const q = plot.map(cur.starts[2 * p], cur.starts[2 * p + 1]);
        if (Math.hypot(ev.x - q.x, ev.y - q.y) < 11) { grab = p; break; }
      }
    } else if (ev.type === 'up' || ev.type === 'leave') { grab = null; }
    else if (ev.type === 'move' && grab !== null && page.pointer.down) {
      const m = plot.unmap(ev.x, ev.y);
      cur.starts[2 * grab] = clamp(m.x, -3.4, 3.4); cur.starts[2 * grab + 1] = clamp(m.y, -3.4, 3.4);
      const r = integrate(cur.starts[2 * grab], cur.starts[2 * grab + 1], REF_STEPS, { ...cfgOf(st), sde: false }, grab);
      cur.refs[grab] = [r[2 * REF_STEPS], r[2 * REF_STEPS + 1]];
      reintegrate(st, grab);
      lad = null;                       // the ladder shares these starts
      page.redraw();
    }
  },
  draw: (page) => {
    const r = page.renderer, ctx = page.ctx, st = page.state;
    r.clear(T.n0);
    if (!cur || !cur.trajs) return;
    const P = st.P | 0, N = cur.N;
    const s = page.step(), si = s ? s.i : N, tcur = si / N, h = 1 / N;

    // ---- layout: main plot on the left, the 4/10/50 ladder on the right ----
    const pad = 12, ladW = Math.max(120, Math.min(190, page.W * 0.22));
    const top = 30, bot = page.H - 34;
    const R = { x: pad, y: top, w: page.W - ladW - 3 * pad, h: bot - top };
    const sc = Math.min(R.w, R.h) / (2 * HALF);
    const cx = R.x + R.w / 2, cy = R.y + R.h / 2;
    const map = (mx, my) => ({ x: cx + mx * sc, y: cy - my * sc });
    plot = { R, map, unmap: (px, py) => ({ x: (px - cx) / sc, y: -(py - cy) / sc }) };

    panelFrame(ctx, R, null);
    drawManifold(ctx, map, 2.1, 0.30);

    // ---- the learned field at the CURRENT time, as arrows ----
    arrowCells = [];
    const nx = 15, ny = Math.max(6, Math.round(15 * R.h / R.w));
    const stepX = R.w / nx, stepY = R.h / ny;
    let vmax = 1e-6;
    const cells = [];
    for (let i = 0; i < nx; i++) for (let j = 0; j < ny; j++) {
      const px = R.x + (i + 0.5) * stepX, py = R.y + (j + 0.5) * stepY;
      const m = plot.unmap(px, py);      // the field is defined everywhere; fill the panel
      const f = field(m.x, m.y, tcur, st.path);
      const mag = Math.hypot(f.ux, f.uy); if (mag > vmax) vmax = mag;
      cells.push({ px, py, mx: m.x, my: m.y, f, mag });
    }
    const alen = Math.min(stepX, stepY) * 0.92;
    for (const c of cells) {
      const k = alen * Math.min(1, c.mag / vmax) / Math.max(c.mag, 1e-6);
      const to = { x: c.px + c.f.ux * k, y: c.py - c.f.uy * k };
      r.arrow({ x: c.px, y: c.py }, to, { color: T.violet, width: 1.2, head: 4, alpha: 0.15 + 0.5 * Math.min(1, c.mag / vmax) });
      arrowCells.push(c);
    }

    // ---- the CONDITIONAL path (dashed ghost): x_t = α(t)·x_end + σ(t)·x_start.
    // This is what the interpolant toggle straightens -- exactly a segment for
    // the linear path, an arc for the trig one. It is NOT the trajectory the
    // sampler integrates; that one is drawn solid below, and measured.
    if (st.guide) {
      ctx.save(); ctx.strokeStyle = alphaOf(T.gold, 0.5); ctx.lineWidth = 1.1;
      if (ctx.setLineDash) ctx.setLineDash([4, 4]);
      for (let p = 0; p < P; p++) {
        const tr = cur.trajs[p], ex = tr[2 * N], ey = tr[2 * N + 1], x0 = tr[0], y0 = tr[1];
        ctx.beginPath();
        for (let k = 0; k <= 32; k++) {
          const cc = coefs(k / 32, st.path), q = map(cc.a * ex + cc.s * x0, cc.a * ey + cc.s * y0);
          if (k === 0) ctx.moveTo(q.x, q.y); else ctx.lineTo(q.x, q.y);
        }
        ctx.stroke();
      }
      ctx.restore();
    }

    // ---- trajectories, revealed up to the current step ----
    ctx.save();
    ctx.lineWidth = 1.9; ctx.strokeStyle = alphaOf(T.accent, 0.85);
    for (let p = 0; p < P; p++) {
      const tr = cur.trajs[p]; ctx.beginPath();
      for (let i = 0; i <= si; i++) { const q = map(tr[2 * i], tr[2 * i + 1]); if (i === 0) ctx.moveTo(q.x, q.y); else ctx.lineTo(q.x, q.y); }
      ctx.stroke();
    }
    ctx.restore();

    // ---- start markers (draggable) + particles at the current step ----
    ctx.save();
    for (let p = 0; p < P; p++) {
      const q0 = map(cur.starts[2 * p], cur.starts[2 * p + 1]);
      ctx.strokeStyle = p === grab ? T.accent : T.n9; ctx.lineWidth = p === grab ? 2 : 1.2;
      ctx.beginPath(); ctx.arc(q0.x, q0.y, 5, 0, 6.2832); ctx.stroke();
    }
    for (let p = 0; p < P; p++) {
      const tr = cur.trajs[p], q = map(tr[2 * si], tr[2 * si + 1]);
      if (st.sde && si > 0) {   // the noise kick of the step just taken
        const prev = map(tr[2 * si - 2], tr[2 * si - 1]);
        ctx.strokeStyle = alphaOf(T.warn, 0.75); ctx.lineWidth = 2;
        ctx.beginPath(); ctx.moveTo(prev.x, prev.y); ctx.lineTo(q.x, q.y); ctx.stroke();
      }
      ctx.fillStyle = T.accent; ctx.beginPath(); ctx.arc(q.x, q.y, 3.4, 0, 6.2832); ctx.fill();
      if (st.sde) { ctx.strokeStyle = alphaOf(T.warn, 0.9); ctx.lineWidth = 1.2; ctx.beginPath(); ctx.arc(q.x, q.y, 5.6, 0, 6.2832); ctx.stroke(); }
    }
    ctx.restore();

    const cf = coefs(tcur, st.path);
    r.label(`t = ${tcur.toFixed(3)}   α=${cf.a.toFixed(3)}  σ=${cf.s.toFixed(3)}   ${st.path === 'linear' ? 'rectified flow (α=t, σ=1−t)' : 'diffusion path (α=sin½πt, σ=cos½πt)'}   ${st.sde ? 'SDE' : 'ODE'}`,
      R.x + 4, top - 10, { color: T.n12, font: '11px ui-monospace, monospace' });
    r.label(`◦ = start (drag me)   ● = particle now   ↗ = learned field at this t   · = data manifold${st.guide ? '   ┄ = conditional path (' + (st.path === 'linear' ? 'straight' : 'curved') + ')' : ''}`,
      R.x + 4, bot + 13, { color: T.n10, font: '10px ui-monospace, monospace' });

    // ---- the 4 / 10 / 50 ladder: same seed, same field, three step counts ----
    const L = buildLadder(st);
    ladRects = [];
    const lx = page.W - ladW - pad, lh = (bot - top) / 3;
    for (let k = 0; k < L.panels.length; k++) {
      const pn = L.panels[k], LR = { x: lx, y: top + k * lh + 3, w: ladW, h: lh - 8 };
      ladRects.push({ ...LR, pn });
      const isCur = pn.N === N;
      panelFrame(ctx, LR, `${pn.N} steps${isCur ? '  ← current' : ''}`, isCur ? T.accent : T.n11);
      const lsc = Math.min(LR.w, LR.h - 26) / (2 * HALF) * 0.92;
      const lcx = LR.x + LR.w / 2, lcy = LR.y + 16 + (LR.h - 26) / 2;
      const lmap = (mx, my) => ({ x: lcx + mx * lsc, y: lcy - my * lsc });
      drawManifold(ctx, lmap, 1.1, 0.28);
      ctx.save(); ctx.fillStyle = alphaOf(T.accent, 0.9);
      for (let p = 0; p < pn.trajs.length; p++) {
        const tr = pn.trajs[p], q = lmap(tr[2 * pn.N], tr[2 * pn.N + 1]);
        ctx.beginPath(); ctx.arc(q.x, q.y, 2.2, 0, 6.2832); ctx.fill();
      }
      ctx.restore();
      r.label(`off ${pn.m.off.toFixed(3)}  Δref ${pn.m.dref.toFixed(3)}`, LR.x + 5, LR.y + LR.h - 5, { color: T.n11, font: '9.5px ui-monospace, monospace' });
    }
    r.label('same seed · same field', lx, top - 10, { color: T.n10, font: '10px ui-monospace, monospace' });

    page.probe = { off: cur.m.off, dref: cur.m.dref, straight: cur.m.straight, steps: N, sde: !!st.sde, path: st.path, lad4: L.panels[0].m.off, odeLad4: L.odeOff4 };

    // ---- hover: field value + the update arithmetic under the cursor --------
    if (page.pointer.over && grab === null) {
      const pt = page.pointer; let tip = null;
      for (let p = 0; p < P && !tip; p++) {
        const tr = cur.trajs[p], q = map(tr[2 * si], tr[2 * si + 1]);
        if (Math.hypot(pt.x - q.x, pt.y - q.y) < 9) {
          const x = tr[2 * si], y = tr[2 * si + 1], f = field(x, y, tcur, st.path);
          const g = st.sde ? st.churn * f.s : 0;
          tip = `particle ${p} @ step ${si}/${N}   x = (${x.toFixed(3)}, ${y.toFixed(3)})\n`
            + `u(x, t=${tcur.toFixed(3)}) = (${f.ux.toFixed(3)}, ${f.uy.toFixed(3)})   h = 1/${N} = ${h.toFixed(4)}\n`
            + `x + u·h = (${(x + f.ux * h).toFixed(3)}, ${(y + f.uy * h).toFixed(3)})${st.sde ? '' : '   ← the whole update (ODE)'}\n`
            + (st.sde ? `+ ½g²·score·h + g√h·z,  g = ${st.churn.toFixed(2)}·σ = ${g.toFixed(3)}\n` : '')
            + (si < N ? `next: (${tr[2 * si + 2].toFixed(3)}, ${tr[2 * si + 3].toFixed(3)})` : `endpoint · off-manifold ${offManifold(x, y).toFixed(3)}`);
        }
      }
      if (!tip) for (const c of arrowCells) {
        if (Math.abs(pt.x - c.px) < stepX / 2 && Math.abs(pt.y - c.py) < stepY / 2) {
          tip = `field at x = (${c.mx.toFixed(2)}, ${c.my.toFixed(2)}), t = ${tcur.toFixed(3)}\n`
            + `u = (${c.f.ux.toFixed(3)}, ${c.f.uy.toFixed(3)})   |u| = ${c.mag.toFixed(3)}\n`
            + `E[data | x] = (${c.f.e1x.toFixed(3)}, ${c.f.e1y.toFixed(3)})\n`
            + `score = (${c.f.sx.toFixed(2)}, ${c.f.sy.toFixed(2)})   a step of h=${h.toFixed(4)} moves ${(c.mag * h).toFixed(4)}`;
          break;
        }
      }
      if (!tip) for (const LR of ladRects) {
        if (pt.x >= LR.x && pt.x <= LR.x + LR.w && pt.y >= LR.y && pt.y <= LR.y + LR.h) {
          tip = `${LR.pn.N} steps, same seed, same field\n`
            + `off-manifold ${LR.pn.m.off.toFixed(3)}  (fine texture lost first)\n`
            + `Δ vs the ${REF_STEPS}-step reference ${LR.pn.m.dref.toFixed(3)}\n`
            + `path/chord ${LR.pn.m.straight.toFixed(3)}`;
          break;
        }
      }
      if (tip) page.setTip(tip);
    }

    // ---- readout -----------------------------------------------------------
    const modeTxt = st.sde ? `SDE (churn ${st.churn.toFixed(2)}) — noise re-injected each step` : 'ODE — deterministic, no noise after t=0';
    let o = `${st.path === 'linear' ? 'rectified-flow' : 'diffusion'} interpolant · ${modeTxt} · ${N} steps · seed ${st.seed}    tier:${r.name}\n`;
    o += `step ${si}/${N}  t=${tcur.toFixed(3)}  ${s ? s.label : ''}\n`;
    o += `endpoints: off-manifold ${cur.m.off.toFixed(4)} (floor ≈ the data's own mode width ${MODE_SD.toFixed(2)}) · Δ vs ${REF_STEPS}-step reference ${cur.m.dref.toFixed(4)} · marginal path/chord ${cur.m.straight.toFixed(4)} (1.00 = a straight line)\n`;
    o += `ladder (same seed, same field): ` + L.panels.map((p) => `${p.N} steps → off ${p.m.off.toFixed(3)}, Δref ${p.m.dref.toFixed(3)}`).join('  ·  ') + '\n';
    o += `the ${st.path === 'linear' ? 'linear' : 'trig'} interpolant makes the CONDITIONAL path ${st.path === 'linear' ? 'exactly straight' : 'an arc'}; the marginal trajectory measured above is a separate quantity, and switching the interpolant does not straighten it by itself (straightening needs reflow — and whether straightness is what buys the step count is disputed).\n`;
    o += st.sde
      ? 'The stochastic sampler self-corrects: a step that lands off the manifold gets pushed back by the score term, so few-step runs stay on-distribution — but Δref is large and stays large, because the seed no longer pins the sample.'
      : 'The deterministic sampler is reproducible and invertible: the same start always gives the same endpoint, and Δref shrinks as the step count rises. The cost is diversity — one noise sample maps to exactly one output.';
    page.setReadout(o);
  },
}).then((page) => {
  window.__diffusionSamplerPage = page;
  const q = new URLSearchParams(location.search);
  const t = page.controls._transport;
  const num = (k) => parseFloat(q.get(k));
  // URL hooks: every control is restorable, so one URL replays one exact run.
  if (q.has('seed')) page.controls.set('seed', num('seed') | 0, { rebuild: true, silent: true });
  if (q.has('P')) page.controls.set('P', num('P') | 0, { rebuild: true, silent: true });
  if (q.has('path')) page.controls.set('path', q.get('path'), { rebuild: true, silent: true });
  if (q.has('sde')) page.controls.set('sde', q.get('sde') === '1' || q.get('sde') === 'true', { rebuild: true, silent: true });
  if (q.has('churn')) page.controls.set('churn', num('churn'), { rebuild: true, silent: true });
  if (q.has('steps')) page.controls.set('steps', num('steps') | 0, { rebuild: true, silent: true });
  if (q.has('guide')) page.controls.set('guide', q.get('guide') === '1' || q.get('guide') === 'true', { silent: true });
  if (t) t.rebuild();
  // ?drag=i,x,y is the headless stand-in for dragging particle i's start marker.
  if (q.has('drag')) {
    const [i, x, y] = q.get('drag').split(',').map(Number);
    if (cur && i >= 0 && 2 * i + 1 < cur.starts.length) {
      cur.starts[2 * i] = clamp(x, -3.4, 3.4); cur.starts[2 * i + 1] = clamp(y, -3.4, 3.4);
      const rr = integrate(cur.starts[2 * i], cur.starts[2 * i + 1], REF_STEPS, { ...cfgOf(page.state), sde: false }, i);
      cur.refs[i] = [rr[2 * REF_STEPS], rr[2 * REF_STEPS + 1]];
      reintegrate(page.state, i); lad = null;
    }
  }
  // ?hover=x,y fakes the cursor (canvas-space px) so the tooltip path renders.
  if (q.has('hover')) { const [hx, hy] = q.get('hover').split(',').map(Number); page.pointer.x = hx; page.pointer.y = hy; page.pointer.over = true; }
  if (q.has('step') || q.has('hover') || q.has('drag')) { if (t) t.pause(); }
  if (q.has('step') && t) t.seek(parseInt(q.get('step'), 10));
  if (q.get('play') === '1' && t) t.play();
  page.redraw();
});
